name: Nightly Build

on:
  push:
    branches: [main, master]
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Run at 2 AM UTC daily

env:
  CARGO_TERM_COLOR: always

jobs:
  build-nightly:
    name: Build Nightly
    runs-on: ubuntu-latest
    if: github.repository_owner == 'd0mkaaa'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.88
        
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-nightly-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build release
      run: cargo build --release --verbose
      env:
        CARGO_NET_GIT_FETCH_WITH_CLI: true
      
    - name: Prepare artifacts
      run: |
        mkdir -p artifacts
        cp target/release/packer artifacts/packer-nightly-linux-x86_64
        cd artifacts
        tar -czf packer-nightly-linux-x86_64.tar.gz packer-nightly-linux-x86_64
        
    - name: Get commit info
      id: commit
      run: |
        echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "DATE=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: nightly
        name: Nightly Build
        body: |
          🌙 **Nightly Build** - Built from latest main branch
          
          **⚠️ Warning**: This is a development build and may be unstable.
          
          **Commit**: ${{ steps.commit.outputs.SHA }}
          **Date**: ${{ steps.commit.outputs.DATE }}
          
          For stable releases, see [releases page](https://github.com/d0mkaaa/packer/releases).
        files: artifacts/packer-nightly-linux-x86_64.tar.gz
        prerelease: true
        generate_release_notes: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}